import { Button, Checkbox, createTheme, Modal, NativeSelect, TextInput, type CSSVariablesResolver } from "@mantine/core";

// Keep the historical mint aliases so every existing viewer uses the same theme.
const accentPalette = ["#eff5ff", "#e0ebff", "#c3d8ff", "#9ec1ff", "#78abfa", "#518ded", "#326fd4", "#285ab5", "#234b90", "#203f74"] as const;

export const libraryTokens = {
  font: {
    ui: '"Segoe UI Variable Text", "Segoe UI", "PingFang SC", "Microsoft YaHei UI", "Microsoft YaHei", "Noto Sans CJK SC", "Noto Sans SC", system-ui, sans-serif',
    mono: '"Cascadia Mono", "SFMono-Regular", Consolas, "Noto Sans Mono", "Microsoft YaHei UI", monospace',
    size: { xs: "12px", sm: "13px", md: "14px", lg: "16px", xl: "20px" },
  },
  radius: { xs: "6px", sm: "10px", md: "14px", lg: "20px", xl: "24px" },
  spacing: { xs: "8px", sm: "12px", md: "16px", lg: "24px", xl: "32px" },
  controlHeight: { xs: "32px", sm: "36px", md: "42px", lg: "50px", xl: "60px" },
} as const;

const dark = {
  "--library-bg": "#14171d",
  "--library-sidebar": "rgba(32, 36, 44, .76)",
  "--library-panel": "#20242d",
  "--library-panel-secondary": "#262b35",
  "--library-elevated": "#303641",
  "--library-hover": "rgba(255, 255, 255, .065)",
  "--library-selected": "rgba(130, 179, 255, .13)",
  "--library-overlay": "rgba(12, 15, 21, .56)",
  "--library-text": "#f1f3f7",
  "--library-text-secondary": "#bec5d1",
  "--library-text-tertiary": "#9ba5b6",
  "--library-text-muted": "#929dad",
  "--library-text-disabled": "#717d90",
  "--library-border-subtle": "rgba(226, 234, 255, .085)",
  "--library-border": "rgba(226, 234, 255, .14)",
  "--library-border-strong": "rgba(226, 234, 255, .24)",
  "--library-mint": "#96bcff",
  "--library-mint-light": "#bed5ff",
  "--library-mint-strong": "#78abfa",
  "--library-mint-veil": "rgba(120, 171, 250, .12)",
  "--library-violet": "#c2b5e3",
  "--library-violet-veil": "rgba(194, 181, 227, .12)",
  "--library-amber": "#e6bf85",
  "--library-amber-veil": "rgba(230, 191, 133, .12)",
  "--library-rose": "#f4a8b0",
  "--library-rose-veil": "rgba(244, 168, 176, .12)",
  "--library-blue": "#96bcff",
  "--library-success": "#93d5b5",
  "--library-warning": "#e6bf85",
  "--library-error": "#f4a8b0",
  "--library-info": "#96bcff",
  "--library-glass": "rgba(34, 39, 48, .76)",
  "--library-glass-solid": "#242a34",
  "--library-glass-highlight": "rgba(255, 255, 255, .12)",
  "--library-canvas": "rgba(24, 28, 36, .68)",
  "--library-card": "#252a34",
  "--library-art": "#2a303b",
  "--library-ambient": "rgba(147, 173, 219, .12)",
  "--library-shadow-card": "0 2px 8px rgba(0, 0, 0, .10)",
  "--library-shadow-raised": "0 8px 24px rgba(0, 0, 0, .20)",
  "--library-shadow-panel": "0 12px 40px rgba(0, 0, 0, .16)",
  "--library-shadow-overlay": "0 24px 72px rgba(0, 0, 0, .32)",
  "--library-ring": "0 0 0 3px rgba(120, 171, 250, .20)",
};

const light: typeof dark = {
  "--library-bg": "#e9edf3",
  "--library-sidebar": "rgba(255, 255, 255, .76)",
  "--library-panel": "#fafbfd",
  "--library-panel-secondary": "#f1f4f8",
  "--library-elevated": "#ffffff",
  "--library-hover": "rgba(39, 61, 96, .055)",
  "--library-selected": "rgba(50, 111, 212, .10)",
  "--library-overlay": "rgba(36, 45, 62, .24)",
  "--library-text": "#252c38",
  "--library-text-secondary": "#49566a",
  "--library-text-tertiary": "#5e6e85",
  "--library-text-muted": "#64738a",
  "--library-text-disabled": "#79889c",
  "--library-border-subtle": "rgba(34, 53, 86, .08)",
  "--library-border": "rgba(34, 53, 86, .13)",
  "--library-border-strong": "rgba(34, 53, 86, .22)",
  "--library-mint": "#285ab5",
  "--library-mint-light": "#234b90",
  "--library-mint-strong": "#326fd4",
  "--library-mint-veil": "rgba(50, 111, 212, .09)",
  "--library-violet": "#71549b",
  "--library-violet-veil": "rgba(113, 84, 155, .09)",
  "--library-amber": "#88601e",
  "--library-amber-veil": "rgba(136, 96, 30, .09)",
  "--library-rose": "#b53d53",
  "--library-rose-veil": "rgba(181, 61, 83, .09)",
  "--library-blue": "#285ab5",
  "--library-success": "#23754f",
  "--library-warning": "#88601e",
  "--library-error": "#b53d53",
  "--library-info": "#285ab5",
  "--library-glass": "rgba(255, 255, 255, .82)",
  "--library-glass-solid": "#fafbfd",
  "--library-glass-highlight": "rgba(255, 255, 255, .92)",
  "--library-canvas": "rgba(250, 252, 255, .62)",
  "--library-card": "#ffffff",
  "--library-art": "#e7ecf3",
  "--library-ambient": "rgba(129, 158, 207, .17)",
  "--library-shadow-card": "0 2px 8px rgba(43, 58, 86, .035)",
  "--library-shadow-raised": "0 8px 24px rgba(43, 58, 86, .10)",
  "--library-shadow-panel": "0 12px 40px rgba(43, 58, 86, .07)",
  "--library-shadow-overlay": "0 24px 72px rgba(43, 58, 86, .18)",
  "--library-ring": "0 0 0 3px rgba(50, 111, 212, .15)",
};

function schemeVariables(scheme: typeof dark) {
  return {
    ...scheme,
    "--library-scanning": scheme["--library-info"],
    "--library-stale": scheme["--library-warning"],
    "--library-missing": scheme["--library-error"],
    "--mantine-color-body": scheme["--library-bg"],
    "--mantine-color-text": scheme["--library-text"],
    "--mantine-color-dimmed": scheme["--library-text-tertiary"],
    "--mantine-primary-color-light": scheme["--library-mint-veil"],
    "--mantine-primary-color-light-color": scheme["--library-mint"],
  };
}

export const libraryCssVariablesResolver: CSSVariablesResolver = (theme) => ({
  variables: {
    "--library-font-ui": theme.fontFamily,
    "--library-font-mono": theme.fontFamilyMonospace,
    "--library-radius-xs": theme.radius.xs,
    "--library-radius-sm": theme.radius.sm,
    "--library-radius-md": theme.radius.md,
    "--library-radius-lg": theme.radius.lg,
    "--library-control-xs": libraryTokens.controlHeight.xs,
    "--library-control-sm": libraryTokens.controlHeight.sm,
    "--library-control-md": libraryTokens.controlHeight.md,
    "--library-control-lg": libraryTokens.controlHeight.lg,
    "--library-control-xl": libraryTokens.controlHeight.xl,
    "--library-glass-filter": "blur(24px) saturate(1.15)",
    "--library-motion-fast": "140ms",
    "--library-motion-normal": "220ms",
    "--library-motion-enter": "260ms",
    "--library-motion-ease": "cubic-bezier(.2, .8, .2, 1)",
  },
  dark: schemeVariables(dark),
  light: schemeVariables(light),
});

export const libraryTheme = createTheme({
  primaryColor: "mint",
  primaryShade: { light: 7, dark: 4 },
  autoContrast: true,
  colors: {
    mint: [...accentPalette],
    dark: ["#f1f3f7", "#bec5d1", "#9ba5b6", "#717d90", "#535e70", "#404a5b", "#303641", "#262b35", "#20242d", "#14171d"],
  },
  fontFamily: libraryTokens.font.ui,
  fontFamilyMonospace: libraryTokens.font.mono,
  headings: { fontFamily: libraryTokens.font.ui, fontWeight: "600" },
  fontSizes: libraryTokens.font.size,
  radius: libraryTokens.radius,
  spacing: libraryTokens.spacing,
  defaultRadius: "sm",
  breakpoints: { xs: "36em", sm: "48em", md: "66.25em", lg: "78.125em", xl: "100em" },
  focusRing: "auto",
  respectReducedMotion: true,
  components: {
    Button: Button.extend({
      defaultProps: { size: "xs", variant: "default" },
      vars: (_theme, props) => ({ root: props.variant === "filled" && (!props.color || props.color === "mint")
        ? { "--button-color": "var(--mantine-primary-color-contrast)" } : {} }),
    }),
    TextInput: TextInput.extend({ defaultProps: { size: "xs" } }),
    NativeSelect: NativeSelect.extend({ defaultProps: { size: "xs" } }),
    Checkbox: Checkbox.extend({ defaultProps: { size: "xs" } }),
    Modal: Modal.extend({ defaultProps: { centered: true, overlayProps: { backgroundOpacity: .35, blur: 8 }, transitionProps: { duration: 220, transition: "fade-down" } } }),
  },
});
